name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build app
      run: |
        pyinstaller --name DTopApp \
                    --windowed \
                    --onedir \
                    --add-data "src:src" \
                    --add-data "ui:ui" \
                    src/ui.py
                    
    - name: Create release directory
      run: |
        mkdir -p release
        cp -r "dist/DTopApp.app" release/
        cd release
        zip -r "DTopApp-macOS.zip" "DTopApp.app"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/DTopApp-macOS.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH.PAT }} 
